# Book settings
title: incomevis
author: Sang T. Truong and Humberto Barreto
logo: logo/logo.png

latex:
  latex_documents:
    targetname: book.tex

html:
  favicon: logo/favicon/favicon.ico
theme: jekyll-theme-modernist
