# Book settings
title: "incomevis: Documentation and User Manual"
description: "<a href="https://scholar.google.com/citations?user=3vc6zDsAAAAJ&hl=en">Sang T. Truong</a> and Humberto Barreto"
logo: logo/logo.png

html:
  favicon: logo/favicon/favicon.ico
theme: jekyll-theme-cayman
