# Book settings
title: "incomevis"
author: "Sang T. Truong and Humberto Barreto"
logo: logo/logo.png

html:
  favicon: logo/favicon/favicon.ico
remote_theme: aksakalli/jekyll-doc-theme@gh-pages

theme: jekyll-theme-cayman